import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  console.log(router);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hello next js</h1>
      <Link href="/movies">
        <a>Movies</a>
      </Link>
      <button onClick={() => router.push("/movies")}>go to page</button>
    </div>
  );
}
